version: '3.8'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/opt/src
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head; uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
